
sysmon_download_url_base: "https://download.sysinternals.com/files"
sysmon_install_location: "c:\\sysmon"
sysmon_download_file: Sysmon
file_ext: .zip
sysmon_config_url: "https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml"