---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'
# set AD trusts ==================================================================================================

- name: Trusts configuration
  hosts: trust
  roles:
  #- { role: 'settings/disable_nat_adapter' , tags: 'disable_nat_adapter'}
  - { role: 'dns_conditional_forwarder', tags: 'dns_conditional_forwarder' }
  - { role: 'trusts', tags: 'trust' }
  #- { role: 'settings/enable_nat_adapter', tags: 'enable_nat_adapter'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    remote_forest: "{{lab.domains[domain].trust}}"
    remote_admin: "Administrator@{{remote_forest}}"
    remote_admin_password: "{{lab.domains[remote_forest].domain_password}}"
    zone_name: "{{remote_forest}}"
    remote_dc: "{{lab.domains[remote_forest].dc}}"
    master_server: "{{hostvars[remote_dc].ansible_host}}"
