---
- name: "Read data files"
  hosts: all
  connection: local
  vars_files:
    - "{{data_path}}/config.json"
  tasks:
    - name: save the Json data to a Variable as a Fact
      set_fact:
        lab: "{{lab}}"

#     - name: Read hostnames from CSV file and return a dictionary
#       community.general.read_csv:
#         path: "{{data_path}}/hostnames.csv"
#         key: host
#         delimiter: ','
#         skipinitialspace: yes
#       register: ad_hostnames
#       delegate_to: localhost
# 
# #    - ansible.builtin.debug:
# #        msg: "Host {{ item.key }} : {{ item.value.name }} "
# #      with_dict: "{{ad_hostnames.dict}}"
# #
# #    - ansible.builtin.debug:
# #        msg: "{{ad_hostnames}}"
# 
#     - name: Read OU from CSV file and return a dictionary
#       read_csv:
#         path: "{{data_path}}/ou.csv"
#         delimiter: ','
#         key: name
#         skipinitialspace: yes
#       register: ad_ou
#       delegate_to: localhost
# 
# #    - ansible.builtin.debug:
# #        msg: "OU: {{ item.key }} : {{ item.value.path }} "
# #      with_dict: "{{ad_ou.dict}}"
# 
#     - name: Read groups from CSV file and return a dictionary
#       read_csv:
#         path: "{{data_path}}/groups.csv"
#         delimiter: ','
#         key: name
#         skipinitialspace: yes
#       register: ad_groups
#       delegate_to: localhost
# 
# #    - ansible.builtin.debug:
# #        msg: "Group: {{ item.key }} : managed_by : {{ item.value.managed_by }}, ou : OU=Groups,{{ad_ou.dict[item.value.ou].path}}"
# #      with_dict: "{{ad_groups.dict}}"
# 
# 
#     - name: Read users from CSV file and return a dictionary
#       read_csv:
#         path: "{{data_path}}/users.csv"
#         delimiter: ','
#         key: name
#         skipinitialspace: yes
#       register: ad_users
#       delegate_to: localhost
# 
# #    - ansible.builtin.debug:
# #        msg: "Users: {{ item.key }}:{{item.value.password}} [{{item.value.groups}}], ou : OU=Users,{{ad_ou.dict[item.value.ou].path}}"
# #      with_dict: "{{ad_users.dict}}"
# 
#     - name: Read users localgroups from CSV file and return a dictionary
#       read_csv:
#         path: "{{data_path}}/users_localgroups.csv"
#         delimiter: ','
#         key: host
#         skipinitialspace: yes
#       register: ad_users_localgroup
#       delegate_to: localhost
# 
#     - name: set domain variable
#       set_fact:
#         domain_withoutext: "{{  domain_name | regex_search('(.+)\\..+', '\\1') | first }}"
#       register: domain_withoutext
# 
#     - name: set domain extension variable
#       set_fact:
#         domain_ext: "{{  domain_name | regex_search('.+\\.(.+)', '\\1') | first }}"
#       register: domain_ext
# 
# #    - ansible.builtin.debug:
# #        msg: "domain name : {{domain_withoutext}}.{{domain_ext}}"
# 
# 