---
- name: "Read data files"
  hosts: domain:extensions
  connection: local
  vars_files:
    - "{{data_path}}/config.json"
  tasks:
    - name: save the Json data to a Variable as a Fact
      set_fact:
        lab: "{{lab}}"
        cacheable: yes