---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

- name: "Disable localuser for Ludus Range"
  hosts: domain
  roles:
    - { role: 'disable_localuser_ludus'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[member_domain].domain_password}}"
