---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"

- name: "Setup enable defender"
  hosts: dc01,dc02,dc03,srv01,srv03
  roles:
    - { role: 'settings/windows_defender', tags: 'windows_defender', windows_defender_status: 'on' }
  vars:
    script_path: "../ad/{{domain_name}}/scripts"

- name: Setup disable defender
  hosts: srv02
  roles:
    - { role: 'settings/windows_defender', tags: 'windows_defender', windows_defender_status: 'off' }
  vars:
    script_path: "../ad/{{domain_name}}/scripts"